### ISSUE TITLE
构建出错##[error]Process completed with exit code 2.

### ISSUE THREAD

**Issue by xiaomoy** [codercaizh/openwrt_package#1]
最新commits
```
2023-01-06T05:49:21.1908976Z make[3]: Entering directory '/home/runner/work/openwrt_package/openwrt_package/openwrt/feeds/small/brook'
2023-01-06T05:49:21.3142565Z mkdir -p /home/runner/work/openwrt_package/openwrt_package/openwrt/dl
2023-01-06T05:49:21.3170806Z SHELL= flock /home/runner/work/openwrt_package/openwrt_package/openwrt/tmp/.brook-20230101.tar.gz.flock -c '  	/home/runner/work/openwrt_package/openwrt_package/openwrt/scripts/download.pl "/home/runner/work/openwrt_package/openwrt_package/openwrt/dl" "brook-20230101.tar.gz" "skip" "" "https://codeload.github.com/txthinking/brook/tar.gz/v20230101?"    '
2023-01-06T05:49:21.3562755Z touch /home/runner/work/openwrt_package/openwrt_package/openwrt/build_dir/target-mipsel_24kc_musl/brook-20230101/.prepared_0dfacca59372d9accf16076fe3ef67bd_6664517399ebbbc92a37c5bb081b5c53_check
2023-01-06T05:49:21.3582728Z . /home/runner/work/openwrt_package/openwrt_package/openwrt/include/shell.sh; gzip -dc /home/runner/work/openwrt_package/openwrt_package/openwrt/dl/brook-20230101.tar.gz | tar -C /home/runner/work/openwrt_package/openwrt_package/openwrt/build_dir/target-mipsel_24kc_musl/brook-20230101/.. -xf -
2023-01-06T05:49:21.3676837Z [ ! -d ./src/ ] || cp -fpR ./src/. /home/runner/work/openwrt_package/openwrt_package/openwrt/build_dir/target-mipsel_24kc_musl/brook-20230101
2023-01-06T05:49:21.3729401Z 
2023-01-06T05:49:21.3730126Z Applying ./patches/010-chore-deps-update-iploc-to-fix-build-with-mips.patch using plaintext: 
2023-01-06T05:49:21.3740574Z patching file go.mod
2023-01-06T05:49:21.3741051Z Hunk #1 FAILED at 8.
2023-01-06T05:49:21.3741871Z 1 out of 1 hunk FAILED -- saving rejects to file go.mod.rej
2023-01-06T05:49:21.3742505Z patching file go.sum
2023-01-06T05:49:21.3743068Z Hunk #1 FAILED at 10.
2023-01-06T05:49:21.3743570Z 1 out of 1 hunk FAILED -- saving rejects to file go.sum.rej
2023-01-06T05:49:21.3745449Z Patch failed!  Please fix ./patches/010-chore-deps-update-iploc-to-fix-build-with-mips.patch!
2023-01-06T05:49:21.3751489Z make[3]: *** [Makefile:51: /home/runner/work/openwrt_package/openwrt_package/openwrt/build_dir/target-mipsel_24kc_musl/brook-20230101/.prepared_0dfacca59372d9accf16076fe3ef67bd_6664517399ebbbc92a37c5bb081b5c53] Error 1
2023-01-06T05:49:21.3752168Z make[3]: Leaving directory '/home/runner/work/openwrt_package/openwrt_package/openwrt/feeds/small/brook'
2023-01-06T05:49:21.3752857Z time: package/feeds/small/brook/compile#0.15#0.05#0.19
2023-01-06T05:49:21.3757774Z     ERROR: package/feeds/small/brook failed to build.
2023-01-06T05:49:21.3770143Z make[2]: *** [package/Makefile:116: package/feeds/small/brook/compile] Error 1
2023-01-06T05:49:21.3770709Z make[2]: Leaving directory '/home/runner/work/openwrt_package/openwrt_package/openwrt'
2023-01-06T05:49:21.3784052Z make[1]: *** [package/Makefile:110: /home/runner/work/openwrt_package/openwrt_package/openwrt/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile] Error 2
2023-01-06T05:49:21.3784660Z make[1]: Leaving directory '/home/runner/work/openwrt_package/openwrt_package/openwrt'
2023-01-06T05:49:21.3785306Z make: *** [/home/runner/work/openwrt_package/openwrt_package/openwrt/include/toplevel.mk:231: world] Error 2
2023-01-06T05:49:21.3915447Z ##[error]Process completed with exit code 2.
```

**Comment by codercaizh** [comment]
> 最新commits
> 
> ```
> 2023-01-06T05:49:21.1908976Z make[3]: Entering directory '/home/runner/work/openwrt_package/openwrt_package/openwrt/feeds/small/brook'
> 2023-01-06T05:49:21.3142565Z mkdir -p /home/runner/work/openwrt_package/openwrt_package/openwrt/dl
> 2023-01-06T05:49:21.3170806Z SHELL= flock /home/runner/work/openwrt_package/openwrt_package/openwrt/tmp/.brook-20230101.tar.gz.flock -c '  	/home/runner/work/openwrt_package/openwrt_package/openwrt/scripts/download.pl "/home/runner/work/openwrt_package/openwrt_package/openwrt/dl" "brook-20230101.tar.gz" "skip" "" "https://codeload.github.com/txthinking/brook/tar.gz/v20230101?"    '
> 2023-01-06T05:49:21.3562755Z touch /home/runner/work/openwrt_package/openwrt_package/openwrt/build_dir/target-mipsel_24kc_musl/brook-20230101/.prepared_0dfacca59372d9accf16076fe3ef67bd_6664517399ebbbc92a37c5bb081b5c53_check
> 2023-01-06T05:49:21.3582728Z . /home/runner/work/openwrt_package/openwrt_package/openwrt/include/shell.sh; gzip -dc /home/runner/work/openwrt_package/openwrt_package/openwrt/dl/brook-20230101.tar.gz | tar -C /home/runner/work/openwrt_package/openwrt_package/openwrt/build_dir/target-mipsel_24kc_musl/brook-20230101/.. -xf -
> 2023-01-06T05:49:21.3676837Z [ ! -d ./src/ ] || cp -fpR ./src/. /home/runner/work/openwrt_package/openwrt_package/openwrt/build_dir/target-mipsel_24kc_musl/brook-20230101
> 2023-01-06T05:49:21.3729401Z 
> 2023-01-06T05:49:21.3730126Z Applying ./patches/010-chore-deps-update-iploc-to-fix-build-with-mips.patch using plaintext: 
> 2023-01-06T05:49:21.3740574Z patching file go.mod
> 2023-01-06T05:49:21.3741051Z Hunk #1 FAILED at 8.
> 2023-01-06T05:49:21.3741871Z 1 out of 1 hunk FAILED -- saving rejects to file go.mod.rej
> 2023-01-06T05:49:21.3742505Z patching file go.sum
> 2023-01-06T05:49:21.3743068Z Hunk #1 FAILED at 10.
> 2023-01-06T05:49:21.3743570Z 1 out of 1 hunk FAILED -- saving rejects to file go.sum.rej
> 2023-01-06T05:49:21.3745449Z Patch failed!  Please fix ./patches/010-chore-deps-update-iploc-to-fix-build-with-mips.patch!
> 2023-01-06T05:49:21.3751489Z make[3]: *** [Makefile:51: /home/runner/work/openwrt_package/openwrt_package/openwrt/build_dir/target-mipsel_24kc_musl/brook-20230101/.prepared_0dfacca59372d9accf16076fe3ef67bd_6664517399ebbbc92a37c5bb081b5c53] Error 1
> 2023-01-06T05:49:21.3752168Z make[3]: Leaving directory '/home/runner/work/openwrt_package/openwrt_package/openwrt/feeds/small/brook'
> 2023-01-06T05:49:21.3752857Z time: package/feeds/small/brook/compile#0.15#0.05#0.19
> 2023-01-06T05:49:21.3757774Z     ERROR: package/feeds/small/brook failed to build.
> 2023-01-06T05:49:21.3770143Z make[2]: *** [package/Makefile:116: package/feeds/small/brook/compile] Error 1
> 2023-01-06T05:49:21.3770709Z make[2]: Leaving directory '/home/runner/work/openwrt_package/openwrt_package/openwrt'
> 2023-01-06T05:49:21.3784052Z make[1]: *** [package/Makefile:110: /home/runner/work/openwrt_package/openwrt_package/openwrt/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile] Error 2
> 2023-01-06T05:49:21.3784660Z make[1]: Leaving directory '/home/runner/work/openwrt_package/openwrt_package/openwrt'
> 2023-01-06T05:49:21.3785306Z make: *** [/home/runner/work/openwrt_package/openwrt_package/openwrt/include/toplevel.mk:231: world] Error 2
> 2023-01-06T05:49:21.3915447Z ##[error]Process completed with exit code 2.
> ```

因为默认都是使用最新的op源码和插件源码编译的，有时候这些插件作者更新了源码，但最新源码可能有问题或者不兼容会导致编译不通过，这里有三个办法可以解决
第一种：耐心等待插件作者修复，或者主动去提醒他们修复，看起来是patch文件不太兼容（前段时间还能编译）；
第二种：把出问题的插件移除掉，从日志里看应该是brook插件有问题，那可以用我在readme里提到的menuconfig命令，取消brook的编译，这个插件主要是一种科学上网协议，很少使用，可以直接取消；
第三种：自己去解决这个不兼容问题，比如可以尝试下回退到上一个brook版本 观察能否编译；

**Comment by codercaizh** [comment]
> 最新commits
> 
> ```
> 2023-01-06T05:49:21.1908976Z make[3]: Entering directory '/home/runner/work/openwrt_package/openwrt_package/openwrt/feeds/small/brook'
> 2023-01-06T05:49:21.3142565Z mkdir -p /home/runner/work/openwrt_package/openwrt_package/openwrt/dl
> 2023-01-06T05:49:21.3170806Z SHELL= flock /home/runner/work/openwrt_package/openwrt_package/openwrt/tmp/.brook-20230101.tar.gz.flock -c '  	/home/runner/work/openwrt_package/openwrt_package/openwrt/scripts/download.pl "/home/runner/work/openwrt_package/openwrt_package/openwrt/dl" "brook-20230101.tar.gz" "skip" "" "https://codeload.github.com/txthinking/brook/tar.gz/v20230101?"    '
> 2023-01-06T05:49:21.3562755Z touch /home/runner/work/openwrt_package/openwrt_package/openwrt/build_dir/target-mipsel_24kc_musl/brook-20230101/.prepared_0dfacca59372d9accf16076fe3ef67bd_6664517399ebbbc92a37c5bb081b5c53_check
> 2023-01-06T05:49:21.3582728Z . /home/runner/work/openwrt_package/openwrt_package/openwrt/include/shell.sh; gzip -dc /home/runner/work/openwrt_package/openwrt_package/openwrt/dl/brook-20230101.tar.gz | tar -C /home/runner/work/openwrt_package/openwrt_package/openwrt/build_dir/target-mipsel_24kc_musl/brook-20230101/.. -xf -
> 2023-01-06T05:49:21.3676837Z [ ! -d ./src/ ] || cp -fpR ./src/. /home/runner/work/openwrt_package/openwrt_package/openwrt/build_dir/target-mipsel_24kc_musl/brook-20230101
> 2023-01-06T05:49:21.3729401Z 
> 2023-01-06T05:49:21.3730126Z Applying ./patches/010-chore-deps-update-iploc-to-fix-build-with-mips.patch using plaintext: 
> 2023-01-06T05:49:21.3740574Z patching file go.mod
> 2023-01-06T05:49:21.3741051Z Hunk #1 FAILED at 8.
> 2023-01-06T05:49:21.3741871Z 1 out of 1 hunk FAILED -- saving rejects to file go.mod.rej
> 2023-01-06T05:49:21.3742505Z patching file go.sum
> 2023-01-06T05:49:21.3743068Z Hunk #1 FAILED at 10.
> 2023-01-06T05:49:21.3743570Z 1 out of 1 hunk FAILED -- saving rejects to file go.sum.rej
> 2023-01-06T05:49:21.3745449Z Patch failed!  Please fix ./patches/010-chore-deps-update-iploc-to-fix-build-with-mips.patch!
> 2023-01-06T05:49:21.3751489Z make[3]: *** [Makefile:51: /home/runner/work/openwrt_package/openwrt_package/openwrt/build_dir/target-mipsel_24kc_musl/brook-20230101/.prepared_0dfacca59372d9accf16076fe3ef67bd_6664517399ebbbc92a37c5bb081b5c53] Error 1
> 2023-01-06T05:49:21.3752168Z make[3]: Leaving directory '/home/runner/work/openwrt_package/openwrt_package/openwrt/feeds/small/brook'
> 2023-01-06T05:49:21.3752857Z time: package/feeds/small/brook/compile#0.15#0.05#0.19
> 2023-01-06T05:49:21.3757774Z     ERROR: package/feeds/small/brook failed to build.
> 2023-01-06T05:49:21.3770143Z make[2]: *** [package/Makefile:116: package/feeds/small/brook/compile] Error 1
> 2023-01-06T05:49:21.3770709Z make[2]: Leaving directory '/home/runner/work/openwrt_package/openwrt_package/openwrt'
> 2023-01-06T05:49:21.3784052Z make[1]: *** [package/Makefile:110: /home/runner/work/openwrt_package/openwrt_package/openwrt/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile] Error 2
> 2023-01-06T05:49:21.3784660Z make[1]: Leaving directory '/home/runner/work/openwrt_package/openwrt_package/openwrt'
> 2023-01-06T05:49:21.3785306Z make: *** [/home/runner/work/openwrt_package/openwrt_package/openwrt/include/toplevel.mk:231: world] Error 2
> 2023-01-06T05:49:21.3915447Z ##[error]Process completed with exit code 2.
> ```

![IMG_20230107_072551](https://user-images.githubusercontent.com/17381647/211116281-e72840b5-404b-4fbd-a22a-8c7a5dcf113b.jpg)
![Screenshot_2023-01-07-07-25-59-312_com android browser](https://user-images.githubusercontent.com/17381647/211116301-d3c37b15-960a-4d51-af50-6794b178810d.jpg)
进插件仓库看了下，确实是五天前作者更新了这个插件导致的编译失败，已经有人提issue反馈这个问题了
https://github.com/kenzok8/small/issues/53
这个issue下面也有临时解决方法，如果你一定要用这个插件，可以也去反馈一下，或者用一下临时方法解决

**Comment by xiaomoy** [comment]
> > 最新commits
> > ```
> > 2023-01-06T05:49:21.1908976Z make[3]: Entering directory '/home/runner/work/openwrt_package/openwrt_package/openwrt/feeds/small/brook'
> > 2023-01-06T05:49:21.3142565Z mkdir -p /home/runner/work/openwrt_package/openwrt_package/openwrt/dl
> > 2023-01-06T05:49:21.3170806Z SHELL= flock /home/runner/work/openwrt_package/openwrt_package/openwrt/tmp/.brook-20230101.tar.gz.flock -c '  	/home/runner/work/openwrt_package/openwrt_package/openwrt/scripts/download.pl "/home/runner/work/openwrt_package/openwrt_package/openwrt/dl" "brook-20230101.tar.gz" "skip" "" "https://codeload.github.com/txthinking/brook/tar.gz/v20230101?"    '
> > 2023-01-06T05:49:21.3562755Z touch /home/runner/work/openwrt_package/openwrt_package/openwrt/build_dir/target-mipsel_24kc_musl/brook-20230101/.prepared_0dfacca59372d9accf16076fe3ef67bd_6664517399ebbbc92a37c5bb081b5c53_check
> > 2023-01-06T05:49:21.3582728Z . /home/runner/work/openwrt_package/openwrt_package/openwrt/include/shell.sh; gzip -dc /home/runner/work/openwrt_package/openwrt_package/openwrt/dl/brook-20230101.tar.gz | tar -C /home/runner/work/openwrt_package/openwrt_package/openwrt/build_dir/target-mipsel_24kc_musl/brook-20230101/.. -xf -
> > 2023-01-06T05:49:21.3676837Z [ ! -d ./src/ ] || cp -fpR ./src/. /home/runner/work/openwrt_package/openwrt_package/openwrt/build_dir/target-mipsel_24kc_musl/brook-20230101
> > 2023-01-06T05:49:21.3729401Z 
> > 2023-01-06T05:49:21.3730126Z Applying ./patches/010-chore-deps-update-iploc-to-fix-build-with-mips.patch using plaintext: 
> > 2023-01-06T05:49:21.3740574Z patching file go.mod
> > 2023-01-06T05:49:21.3741051Z Hunk #1 FAILED at 8.
> > 2023-01-06T05:49:21.3741871Z 1 out of 1 hunk FAILED -- saving rejects to file go.mod.rej
> > 2023-01-06T05:49:21.3742505Z patching file go.sum
> > 2023-01-06T05:49:21.3743068Z Hunk #1 FAILED at 10.
> > 2023-01-06T05:49:21.3743570Z 1 out of 1 hunk FAILED -- saving rejects to file go.sum.rej
> > 2023-01-06T05:49:21.3745449Z Patch failed!  Please fix ./patches/010-chore-deps-update-iploc-to-fix-build-with-mips.patch!
> > 2023-01-06T05:49:21.3751489Z make[3]: *** [Makefile:51: /home/runner/work/openwrt_package/openwrt_package/openwrt/build_dir/target-mipsel_24kc_musl/brook-20230101/.prepared_0dfacca59372d9accf16076fe3ef67bd_6664517399ebbbc92a37c5bb081b5c53] Error 1
> > 2023-01-06T05:49:21.3752168Z make[3]: Leaving directory '/home/runner/work/openwrt_package/openwrt_package/openwrt/feeds/small/brook'
> > 2023-01-06T05:49:21.3752857Z time: package/feeds/small/brook/compile#0.15#0.05#0.19
> > 2023-01-06T05:49:21.3757774Z     ERROR: package/feeds/small/brook failed to build.
> > 2023-01-06T05:49:21.3770143Z make[2]: *** [package/Makefile:116: package/feeds/small/brook/compile] Error 1
> > 2023-01-06T05:49:21.3770709Z make[2]: Leaving directory '/home/runner/work/openwrt_package/openwrt_package/openwrt'
> > 2023-01-06T05:49:21.3784052Z make[1]: *** [package/Makefile:110: /home/runner/work/openwrt_package/openwrt_package/openwrt/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile] Error 2
> > 2023-01-06T05:49:21.3784660Z make[1]: Leaving directory '/home/runner/work/openwrt_package/openwrt_package/openwrt'
> > 2023-01-06T05:49:21.3785306Z make: *** [/home/runner/work/openwrt_package/openwrt_package/openwrt/include/toplevel.mk:231: world] Error 2
> > 2023-01-06T05:49:21.3915447Z ##[error]Process completed with exit code 2.
> > ```
> 
> ![IMG_20230107_072551](https://user-images.githubusercontent.com/17381647/211116281-e72840b5-404b-4fbd-a22a-8c7a5dcf113b.jpg) ![Screenshot_2023-01-07-07-25-59-312_com android browser](https://user-images.githubusercontent.com/17381647/211116301-d3c37b15-960a-4d51-af50-6794b178810d.jpg) 进插件仓库看了下，确实是五天前作者更新了这个插件导致的编译失败，已经有人提issue反馈这个问题了 [kenzok8/small#53](https://github.com/kenzok8/small/issues/53) 这个issue下面也有临时解决方法，如果你一定要用这个插件，可以也去反馈一下，或者用一下临时方法解决

好的，那只能等作者更新了，我就说看commit没啥问题，咋就一直构建失败呢😂

**Comment by codercaizh** [comment]
> > > 最新commits
> > > ```
> > > 2023-01-06T05:49:21.1908976Z make[3]: Entering directory '/home/runner/work/openwrt_package/openwrt_package/openwrt/feeds/small/brook'
> > > 2023-01-06T05:49:21.3142565Z mkdir -p /home/runner/work/openwrt_package/openwrt_package/openwrt/dl
> > > 2023-01-06T05:49:21.3170806Z SHELL= flock /home/runner/work/openwrt_package/openwrt_package/openwrt/tmp/.brook-20230101.tar.gz.flock -c '  	/home/runner/work/openwrt_package/openwrt_package/openwrt/scripts/download.pl "/home/runner/work/openwrt_package/openwrt_package/openwrt/dl" "brook-20230101.tar.gz" "skip" "" "https://codeload.github.com/txthinking/brook/tar.gz/v20230101?"    '
> > > 2023-01-06T05:49:21.3562755Z touch /home/runner/work/openwrt_package/openwrt_package/openwrt/build_dir/target-mipsel_24kc_musl/brook-20230101/.prepared_0dfacca59372d9accf16076fe3ef67bd_6664517399ebbbc92a37c5bb081b5c53_check
> > > 2023-01-06T05:49:21.3582728Z . /home/runner/work/openwrt_package/openwrt_package/openwrt/include/shell.sh; gzip -dc /home/runner/work/openwrt_package/openwrt_package/openwrt/dl/brook-20230101.tar.gz | tar -C /home/runner/work/openwrt_package/openwrt_package/openwrt/build_dir/target-mipsel_24kc_musl/brook-20230101/.. -xf -
> > > 2023-01-06T05:49:21.3676837Z [ ! -d ./src/ ] || cp -fpR ./src/. /home/runner/work/openwrt_package/openwrt_package/openwrt/build_dir/target-mipsel_24kc_musl/brook-20230101
> > > 2023-01-06T05:49:21.3729401Z 
> > > 2023-01-06T05:49:21.3730126Z Applying ./patches/010-chore-deps-update-iploc-to-fix-build-with-mips.patch using plaintext: 
> > > 2023-01-06T05:49:21.3740574Z patching file go.mod
> > > 2023-01-06T05:49:21.3741051Z Hunk #1 FAILED at 8.
> > > 2023-01-06T05:49:21.3741871Z 1 out of 1 hunk FAILED -- saving rejects to file go.mod.rej
> > > 2023-01-06T05:49:21.3742505Z patching file go.sum
> > > 2023-01-06T05:49:21.3743068Z Hunk #1 FAILED at 10.
> > > 2023-01-06T05:49:21.3743570Z 1 out of 1 hunk FAILED -- saving rejects to file go.sum.rej
> > > 2023-01-06T05:49:21.3745449Z Patch failed!  Please fix ./patches/010-chore-deps-update-iploc-to-fix-build-with-mips.patch!
> > > 2023-01-06T05:49:21.3751489Z make[3]: *** [Makefile:51: /home/runner/work/openwrt_package/openwrt_package/openwrt/build_dir/target-mipsel_24kc_musl/brook-20230101/.prepared_0dfacca59372d9accf16076fe3ef67bd_6664517399ebbbc92a37c5bb081b5c53] Error 1
> > > 2023-01-06T05:49:21.3752168Z make[3]: Leaving directory '/home/runner/work/openwrt_package/openwrt_package/openwrt/feeds/small/brook'
> > > 2023-01-06T05:49:21.3752857Z time: package/feeds/small/brook/compile#0.15#0.05#0.19
> > > 2023-01-06T05:49:21.3757774Z     ERROR: package/feeds/small/brook failed to build.
> > > 2023-01-06T05:49:21.3770143Z make[2]: *** [package/Makefile:116: package/feeds/small/brook/compile] Error 1
> > > 2023-01-06T05:49:21.3770709Z make[2]: Leaving directory '/home/runner/work/openwrt_package/openwrt_package/openwrt'
> > > 2023-01-06T05:49:21.3784052Z make[1]: *** [package/Makefile:110: /home/runner/work/openwrt_package/openwrt_package/openwrt/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile] Error 2
> > > 2023-01-06T05:49:21.3784660Z make[1]: Leaving directory '/home/runner/work/openwrt_package/openwrt_package/openwrt'
> > > 2023-01-06T05:49:21.3785306Z make: *** [/home/runner/work/openwrt_package/openwrt_package/openwrt/include/toplevel.mk:231: world] Error 2
> > > 2023-01-06T05:49:21.3915447Z ##[error]Process completed with exit code 2.
> > > ```
> > 
> > 
> > ![IMG_20230107_072551](https://user-images.githubusercontent.com/17381647/211116281-e72840b5-404b-4fbd-a22a-8c7a5dcf113b.jpg) ![Screenshot_2023-01-07-07-25-59-312_com android browser](https://user-images.githubusercontent.com/17381647/211116301-d3c37b15-960a-4d51-af50-6794b178810d.jpg) 进插件仓库看了下，确实是五天前作者更新了这个插件导致的编译失败，已经有人提issue反馈这个问题了 [kenzok8/small#53](https://github.com/kenzok8/small/issues/53) 这个issue下面也有临时解决方法，如果你一定要用这个插件，可以也去反馈一下，或者用一下临时方法解决
> 
> 好的，那只能等作者更新了，我就说看commit没啥问题，咋就一直构建失败呢😂

https://github.com/codercaizh/openwrt_package/commit/5b021e19d4453e51db319980d10b04b88e510b92
我加了行脚本临时解决了插件的问题，可以试一下编译看看，目前我也在用github action验证。

**Comment by xiaomoy** [comment]
> > > > 最新commits
> > > > ```
> > > > 2023-01-06T05:49:21.1908976Z make[3]: Entering directory '/home/runner/work/openwrt_package/openwrt_package/openwrt/feeds/small/brook'
> > > > 2023-01-06T05:49:21.3142565Z mkdir -p /home/runner/work/openwrt_package/openwrt_package/openwrt/dl
> > > > 2023-01-06T05:49:21.3170806Z SHELL= flock /home/runner/work/openwrt_package/openwrt_package/openwrt/tmp/.brook-20230101.tar.gz.flock -c '  	/home/runner/work/openwrt_package/openwrt_package/openwrt/scripts/download.pl "/home/runner/work/openwrt_package/openwrt_package/openwrt/dl" "brook-20230101.tar.gz" "skip" "" "https://codeload.github.com/txthinking/brook/tar.gz/v20230101?"    '
> > > > 2023-01-06T05:49:21.3562755Z touch /home/runner/work/openwrt_package/openwrt_package/openwrt/build_dir/target-mipsel_24kc_musl/brook-20230101/.prepared_0dfacca59372d9accf16076fe3ef67bd_6664517399ebbbc92a37c5bb081b5c53_check
> > > > 2023-01-06T05:49:21.3582728Z . /home/runner/work/openwrt_package/openwrt_package/openwrt/include/shell.sh; gzip -dc /home/runner/work/openwrt_package/openwrt_package/openwrt/dl/brook-20230101.tar.gz | tar -C /home/runner/work/openwrt_package/openwrt_package/openwrt/build_dir/target-mipsel_24kc_musl/brook-20230101/.. -xf -
> > > > 2023-01-06T05:49:21.3676837Z [ ! -d ./src/ ] || cp -fpR ./src/. /home/runner/work/openwrt_package/openwrt_package/openwrt/build_dir/target-mipsel_24kc_musl/brook-20230101
> > > > 2023-01-06T05:49:21.3729401Z 
> > > > 2023-01-06T05:49:21.3730126Z Applying ./patches/010-chore-deps-update-iploc-to-fix-build-with-mips.patch using plaintext: 
> > > > 2023-01-06T05:49:21.3740574Z patching file go.mod
> > > > 2023-01-06T05:49:21.3741051Z Hunk #1 FAILED at 8.
> > > > 2023-01-06T05:49:21.3741871Z 1 out of 1 hunk FAILED -- saving rejects to file go.mod.rej
> > > > 2023-01-06T05:49:21.3742505Z patching file go.sum
> > > > 2023-01-06T05:49:21.3743068Z Hunk #1 FAILED at 10.
> > > > 2023-01-06T05:49:21.3743570Z 1 out of 1 hunk FAILED -- saving rejects to file go.sum.rej
> > > > 2023-01-06T05:49:21.3745449Z Patch failed!  Please fix ./patches/010-chore-deps-update-iploc-to-fix-build-with-mips.patch!
> > > > 2023-01-06T05:49:21.3751489Z make[3]: *** [Makefile:51: /home/runner/work/openwrt_package/openwrt_package/openwrt/build_dir/target-mipsel_24kc_musl/brook-20230101/.prepared_0dfacca59372d9accf16076fe3ef67bd_6664517399ebbbc92a37c5bb081b5c53] Error 1
> > > > 2023-01-06T05:49:21.3752168Z make[3]: Leaving directory '/home/runner/work/openwrt_package/openwrt_package/openwrt/feeds/small/brook'
> > > > 2023-01-06T05:49:21.3752857Z time: package/feeds/small/brook/compile#0.15#0.05#0.19
> > > > 2023-01-06T05:49:21.3757774Z     ERROR: package/feeds/small/brook failed to build.
> > > > 2023-01-06T05:49:21.3770143Z make[2]: *** [package/Makefile:116: package/feeds/small/brook/compile] Error 1
> > > > 2023-01-06T05:49:21.3770709Z make[2]: Leaving directory '/home/runner/work/openwrt_package/openwrt_package/openwrt'
> > > > 2023-01-06T05:49:21.3784052Z make[1]: *** [package/Makefile:110: /home/runner/work/openwrt_package/openwrt_package/openwrt/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile] Error 2
> > > > 2023-01-06T05:49:21.3784660Z make[1]: Leaving directory '/home/runner/work/openwrt_package/openwrt_package/openwrt'
> > > > 2023-01-06T05:49:21.3785306Z make: *** [/home/runner/work/openwrt_package/openwrt_package/openwrt/include/toplevel.mk:231: world] Error 2
> > > > 2023-01-06T05:49:21.3915447Z ##[error]Process completed with exit code 2.
> > > > ```
> > > 
> > > 
> > > ![IMG_20230107_072551](https://user-images.githubusercontent.com/17381647/211116281-e72840b5-404b-4fbd-a22a-8c7a5dcf113b.jpg) ![Screenshot_2023-01-07-07-25-59-312_com android browser](https://user-images.githubusercontent.com/17381647/211116301-d3c37b15-960a-4d51-af50-6794b178810d.jpg) 进插件仓库看了下，确实是五天前作者更新了这个插件导致的编译失败，已经有人提issue反馈这个问题了 [kenzok8/small#53](https://github.com/kenzok8/small/issues/53) 这个issue下面也有临时解决方法，如果你一定要用这个插件，可以也去反馈一下，或者用一下临时方法解决
> > 
> > 
> > 好的，那只能等作者更新了，我就说看commit没啥问题，咋就一直构建失败呢😂
> 
> [5b021e1](https://github.com/codercaizh/openwrt_package/commit/5b021e19d4453e51db319980d10b04b88e510b92) 我加了行脚本临时解决了插件的问题，可以试一下编译看看，目前我也在用github action验证。

试了，可以正常编译
